// This file has been generated by Specta. DO NOT EDIT.

export type ApiEvent = { Debug: string }

export type ApiRecv = { Map: MapApiRecv } | { TileLayer: { id: string; recv: TileLayerApiRecv } } | { Debug: string }

export type CtrlRecv = "Init" | "Stop"

export type CtrlResp = "Created" | "Initialized" | "Ready" | "Stopped"

export type MapApiRecv = { SetView: MapView }

export type MapView = { lat: number; lng: number; zoom: number }

export type TileLayer = { tiles: string; options: TileLayerOptions }

export type TileLayerApiRecv = { Add: TileLayer } | { SetOpacity: number } | "Remove"

export type TileLayerOptions = { maxZoom: number | null; attribution: string | null; opacity: number | null }

